services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./case-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret

  frontend:
    build:
      context: ./case-frontend
      dockerfile: Dockerfile
    command: pnpm run preview -- --host 0.0.0.0

    ports:
      - "4173:4173"
    working_dir: /app
